version: 2
jobs:
  build:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: start-server
          command: npm start
          background: true
      - run:
          name: test
          command: npm run test:bs
